### ISSUE TITLE
`_list_oids_traverse` is much slower than `_list_oids`.

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc-objects#178]
I have no context behind the introduction of [_list_oids_traverse](https://github.com/iterative/dvc-objects/blob/76db927c585f89e0d7ebdc7c481c6ebba77a91a2/src/dvc_objects/db.py#L251) but, on every scenario and remote size I have tested, it is slower than plain `_list_oids`.

This has a negative performance impact for many operations, I reported the `dvc gc` case in 

I am guessing the idea of list traverse was introduced before the adoption of fsspec as backend. 
The reality today is that the combination of `ThreadPoolExecutor` and the single fsspec async loop causes the operation to be significantly slower than a single `_list_oids` call.

**Comment by dberenbaum** [comment]
@daavoo Do you have results to share for different scenarios?

**Comment by pmrowla** [comment]
for context on traverse/no-traverse:

https://iterative.ai/blog/dvc-vs-rclone
https://github.com/iterative/dvc/issues/3488
https://github.com/iterative/dvc/pull/3501

---

The main premise behind the optimization should still be valid even with fsspec/asyncio. For push/fetch/status it's better for us to estimate size of the remote based on the size of a single prefix, and then try and determine whether it's faster to finish listing the full remote or make individual `exists` calls.

For `gc` the size estimation isn't relevant since we have to list the full remote regardless, but the original implementation also included parallelizing the full listing by prefix which was a valid `gc` optimization. But this parallelization (via the threadpoolexecutor) is probably what is broken now, since with fsspec this all gets done in the single async thread instead.

Fixing this is really related to getting rid of our ThreadPoolExecutor usage in favor of letting fsspec handle the parallelization w/asyncio instead.

**Comment by dberenbaum** [comment]
@daavoo Do you have those times and comparisons to AWS CLI? It would be helpful to get an idea if it's 1.5x slower vs 10x slower.
